<a href="https://colab.research.google.com/github/arka10jas/TEST/blob/master/UROJAHAJ_ER_DAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

Importing the Data Set

In [3]:
train_data= pd.read_excel(r"Data_Train.xlsx")
pd.set_option('display.max_columns',None)
train_data.head()

FileNotFoundError: ignored

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [ ]:
train_data["Duration"].value_counts()

2h 50m     550
1h 30m     386
2h 55m     337
2h 45m     337
2h 35m     329
3h         261
2h 20m     238
2h 30m     220
2h 40m     158
1h 25m     135
2h 15m     135
2h 25m      98
13h 30m     97
13h 20m     89
3h 15m      88
7h 30m      86
9h 30m      85
8h 40m      81
7h 15m      79
3h 5m       78
5h 30m      72
7h 35m      71
8h          68
7h 5m       65
9h 50m      64
9h          64
5h          63
11h         62
11h 45m     62
5h 15m      62
14h 25m     61
1h 20m      61
6h 35m      60
12h 10m     57
22h 55m     57
10h 30m     57
12h 45m     56
5h 45m      54
16h 5m      53
12h 30m     52
7h 20m      52
11h 30m     52
15h 10m     51
4h 55m      51
8h 25m      50
10h 15m     50
10h         49
12h         49
10h 25m     49
12h 15m     48
6h 15m      47
11h 5m      45
5h 20m      45
26h 55m     44
9h 15m      42
13h         42
14h 5m      42
8h 55m      42
20h 10m     41
9h 20m      41
9h 35m      41
17h 5m      40
23h 40m     40
3h 10m      40
26h 35m     39
21h 15m     39
5h 5m       38
14h 35m     38
27h 35m     38
6h 30m      38
6h 25m      37
23h 50m     37
13h 15m     36
8h 30m      36
12h 25m     36
11h 15m     36
14h         36
13h 25m     36
18h 45m     36
15h 20m     35
4h 30m      35
21h 35m     35
25h 45m     35
13h 50m     35
15h 25m     35
4h 50m      35
27h 20m     34
8h 20m      34
18h 20m     33
15h 30m     33
16h 45m     33
27h         32
14h 20m     31
12h 20m     31
5h 25m      31
12h 35m     31
7h 45m      31
23h 15m     30
5h 55m      30
24h 45m     30
15h         30
23h 30m     30
21h 25m     30
8h 10m      30
14h 30m     29
10h 20m     29
10h 40m     29
26h 20m     29
6h 20m      29
9h 5m       29
26h 10m     29
6h 5m       29
9h 45m      28
19h 55m     28
13h 55m     28
16h 15m     28
29h 20m     28
22h         27
5h 10m      27
7h 40m      27
26h         27
24h         27
9h 10m      26
14h 55m     26
19h 25m     26
6h          26
12h 55m     26
28h 50m     25
6h 10m      25
22h 5m      25
5h 35m      25
8h 35m      25
1h 15m      24
7h 50m      24
23h         24
15h 40m     24
24h 55m     24
11h 25m     24
7h 55m      24
16h 50m     24
10h 10m     23
24h 35m     23
4h 40m      23
6h 40m      23
11h 50m     23
23h 35m     23
3h 40m      23
20h         22
22h 30m     22
16h 55m     22
23h 10m     22
24h 50m     22
22h 45m     22
28h 20m     22
14h 50m     21
11h 55m     21
20h 55m     21
13h 45m     21
5h 40m      21
25h 30m     21
27h 5m      21
7h          21
23h 45m     21
4h 35m      21
12h 40m     20
24h 30m     20
11h 40m     20
10h 55m     20
25h 50m     20
8h 15m      20
17h 25m     20
15h 55m     19
16h         19
26h 50m     19
12h 5m      19
20h 20m     19
25h 55m     19
21h 20m     19
14h 45m     19
4h 25m      19
22h 10m     18
21h 40m     18
10h 35m     17
18h 25m     17
25h 20m     17
27h 10m     17
24h 40m     17
22h 15m     17
18h 10m     17
20h 15m     17
6h 55m      17
8h 5m       17
26h 30m     16
20h 25m     16
24h 10m     16
16h 10m     16
1h 35m      15
30h 30m     15
27h 40m     15
27h 45m     15
22h 35m     15
19h 5m      15
10h 45m     14
26h 40m     14
25h 35m     14
25h 5m      14
13h 10m     14
30h 20m     14
23h 20m     14
14h 10m     14
19h 30m     14
5h 50m      13
9h 25m      13
10h 50m     13
18h         13
25h 40m     13
8h 45m      13
38h         13
17h 45m     12
15h 15m     12
19h 40m     12
20h 35m     12
38h 15m     12
29h 35m     12
28h 5m      12
25h         12
21h 5m      12
21h 10m     12
4h          12
17h 55m     11
14h 15m     11
23h 5m      11
16h 35m     11
22h 25m     11
33h 15m     11
28h         11
11h 35m     11
17h 20m     11
19h 15m     10
17h 35m     10
4h 45m      10
9h 40m      10
16h 25m      9
25h 15m      9
21h 55m      9
15h 5m       9
25h 25m      9
19h          9
29h 5m       9
26h 15m      9
16h 20m      9
23h 55m      9
14h 40m      9
37h 20m      8
8h 50m       8
37h 25m      8
15h 45m      8
21h 45m      8
29h 55m      8
17h 30m      8
4h 5m        8
20h 45m      8
19h 45m      8
26h 25m      8
15h 35m      7
6h 45m       7
28h 15m      7
24h 15m      7
18h 50m      7
30h 40m      7
16h 40m      7
19h 10m      7
17h 15m      7
18h 30m      7
11h 20m      7
36h 10m      6
21h          6
17h 40m      5
28h 25m      5
28h 40m      5
3h 35m       5
29h 50m      5
10h 5m       5
38h 20m      5
30h 55m      5
15h 50m      5
13h 5m       5
32h 5m       5
7h 25m       5
21h 30m      4
4h 15m       4
38h 35m      4
22h 40m      4
24h 25m      4
21h 50m      4
26h 45m      4
24h 5m       4
23h 25m      4
28h 10m      4
12h 50m      3
4h 20m       3
35h 5m       3
13h 40m      3
24h 20m      3
25h 10m      3
30h          3
3h 50m       3
17h 50m      3
16h 30m      3
18h 35m      3
18h 40m      3
26h 5m       3
18h 15m      3
27h 50m      3
19h 20m      2
9h 55m       2
18h 55m      2
30h 45m      2
39h 5m       2
35h 15m      2
20h 5m       2
20h 40m      2
7h 10m       2
28h 55m      2
17h 10m      2
6h 50m       2
34h 30m      2
31h 40m      2
34h 25m      2
32h 30m      2
19h 35m      2
3h 55m       2
31h 55m      2
27h 25m      2
34h 5m       2
11h 10m      2
20h 50m      2
34h          2
27h 30m      1
35h 20m      1
41h 20m      1
29h 40m      1
36h 25m      1
29h 10m      1
32h 55m      1
35h 35m      1
4h 10m       1
40h 20m      1
42h 45m      1
33h 20m      1
33h 45m      1
19h 50m      1
27h 55m      1
42h 5m       1
37h 10m      1
31h 30m      1
47h          1
31h 50m      1
30h 25m      1
5m           1
30h 10m      1
30h 15m      1
32h 20m      1
29h 30m      1
3h 25m       1
28h 30m      1
47h 40m      1
13h 35m      1
Name: Duration, dtype: int64

In [ ]:
train_data.dropna(inplace=True)

In [ ]:
train_data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

EDA

In [ ]:
train_data["Journey_Day"]=pd.to_datetime(train_data["Date_of_Journey"], format="%d/%m/%Y").dt.day
train_data["Journey_Month"]=pd.to_datetime(train_data["Date_of_Journey"], format="%d/%m/%Y").dt.month
train_data.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3

In [ ]:

train_data.drop(["Date_of_Journey"], axis = 1, inplace = True)

In [ ]:
train_data.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3

Extracting Date and Time

In [1]:
train_data["Dep_Hour"]=pd.to_datetime(train_data["Dep_Time"]).dt.hour
train_data["Dep_Min"]=pd.to_datetime(train_data["Dep_Time"]).dt.minute

NameError: ignored